import { convertFileSrc, invoke } from "@tauri-apps/api/core";
import type { Animation, AnimationInput, AnimationTemplate, Asset, AssetPack, AssetVersion, BackgroundJob, Conversation, ExportResult, FrameOptimizationResult, GenerationManifest, ImageProviderInput, Message, MotionPlan, ProceduralVfxInput, ProjectBackup, ProviderConnectionTest, ProviderRequestOptions, ProviderStatus, QualityReport, ReferenceCategory, ReferenceImage, RigFitReport, RigInput, RigRenderResult, RigSuggestion, Rig, SidebarSnapshot, SpriteSheet, SpriteSheetInput, TemplateApplication, TerrainExportInput, TerrainExportResult, VfxEffect, Workspace, Worktree, WorktreeKind } from "$lib/types";

export const api = {
  listWorkspaces: () => invoke<Workspace[]>("list_workspaces"),
  loadSidebarState: (workspaceId?: string) => invoke<SidebarSnapshot>("load_sidebar_state", { workspaceId: workspaceId ?? null }),
  createWorkspace: (name: string, path: string) => invoke<Workspace>("create_workspace", { name, path }),
  openWorkspace: (path: string) => invoke<Workspace>("open_workspace", { path }),
  touchWorkspace: (id: string) => invoke<Workspace>("touch_workspace", { id }),
  renameWorkspace: (id: string, name: string) => invoke<void>("rename_workspace", { id, name }),
  removeWorkspace: (id: string) => invoke<void>("remove_workspace", { id }),
  deleteWorkspace: (id: string) => invoke<void>("delete_workspace", { id }),
  createProjectBackup: (projectId: string, destinationDirectory: string) => invoke<ProjectBackup>("create_project_backup", { projectId, destinationDirectory }),
  restoreProjectBackup: (projectId: string, backupPath: string) => invoke<Workspace>("restore_project_backup", { projectId, backupPath }),
  importProjectBackup: (backupPath: string, destinationPath: string) => invoke<Workspace>("import_project_backup", { backupPath, destinationPath }),
  listWorktrees: (projectId: string) => invoke<Worktree[]>("list_worktrees", { projectId }),
  createWorktree: (projectId: string, name: string, kind: WorktreeKind, description?: string) => invoke<Worktree>("create_worktree", { projectId, name, kind, description }),
  updateWorktree: (id: string, name: string, description?: string) => invoke<Worktree>("update_worktree", { id, name, description }),
  deleteWorktree: (id: string) => invoke<void>("delete_worktree", { id }),
  listWorktreeAssetIds: (worktreeId: string) => invoke<string[]>("list_worktree_asset_ids", { worktreeId }),
  linkAssetToWorktree: (worktreeId: string, assetId: string, relationship: "owned" | "referenced" = "owned") => invoke<void>("link_asset_to_worktree", { worktreeId, assetId, relationship }),
  listConversations: (workspaceId: string, worktreeId?: string) => invoke<Conversation[]>("list_conversations", { workspaceId, worktreeId: worktreeId ?? null }),
  listArchivedConversations: (workspaceId: string) => invoke<Conversation[]>("list_archived_conversations", { workspaceId }),
  createConversation: (workspaceId: string, worktreeId?: string, title?: string, provider?: string) => invoke<Conversation>("create_conversation", { workspaceId, worktreeId: worktreeId ?? null, title, provider }),
  renameConversation: (id: string, title: string) => invoke<void>("rename_conversation", { id, title }),
  switchConversationProvider: (id: string, provider: string) => invoke<Conversation>("switch_conversation_provider", { id, provider }),
  archiveConversation: (id: string) => invoke<void>("archive_conversation", { id }),
  restoreConversation: (id: string) => invoke<Conversation>("restore_conversation", { id }),
  deleteConversation: (id: string) => invoke<void>("delete_conversation", { id }),
  listMessages: (conversationId: string) => invoke<Message[]>("list_messages", { conversationId }),
  updateMessageMetadata: (id: string, metadata: Record<string, unknown>) => invoke<void>("update_message_metadata", { id, metadata }),
  detectProviders: () => invoke<ProviderStatus[]>("detect_providers"),
  saveImageProvider: (input: ImageProviderInput) => invoke<ProviderStatus>("save_image_provider", { input }),
  deleteImageProvider: (id: string) => invoke<void>("delete_image_provider", { id }),
  testImageProvider: (input: ImageProviderInput) => invoke<ProviderConnectionTest>("test_image_provider", { input }),
  startProviderMessage: (conversationId: string, prompt: string, context?: string, options?: ProviderRequestOptions) => invoke<string>("start_provider_message", { conversationId, prompt, context, options }),
  cancelProviderRequest: (requestId: string) => invoke<void>("cancel_provider_request", { requestId }),
  planMotion: (prompt: string, generation: ProviderRequestOptions["generation"]) => invoke<MotionPlan>("plan_motion", { prompt, generation }),
  scanAssets: (workspaceId: string) => invoke<Asset[]>("scan_assets", { workspaceId }),
  listAssets: (workspaceId: string) => invoke<Asset[]>("list_assets", { workspaceId }),
  getGenerationManifest: (workspaceId: string) => invoke<GenerationManifest | null>("get_generation_manifest", { workspaceId }),
  getGenerationFingerprint: (workspaceId: string) => invoke<string | null>("get_generation_fingerprint", { workspaceId }),
  scanGenerationAssets: (workspaceId: string) => invoke<Asset[]>("scan_generation_assets", { workspaceId }),
  listAssetPacks: (workspaceId: string) => invoke<AssetPack[]>("list_asset_packs", { workspaceId }),
  importAsset: (workspaceId: string, sourcePath: string, category: string) => invoke<Asset>("import_asset", { workspaceId, sourcePath, category }),
  renameAsset: (id: string, name: string) => invoke<Asset>("rename_asset", { id, name }),
  deleteAsset: (id: string) => invoke<void>("delete_asset", { id }),
  exportAsset: (id: string) => invoke<ExportResult>("export_asset", { id }),
  exportGodotTileset: (input: TerrainExportInput) => invoke<TerrainExportResult>("export_godot_tileset", { input }),
  listAssetVersions: (assetId: string) => invoke<AssetVersion[]>("list_asset_versions", { assetId }),
  listReferenceImages: (worktreeId: string) => invoke<ReferenceImage[]>("list_reference_images", { worktreeId }),
  importReferenceImage: (worktreeId: string, sourcePath: string, category: ReferenceCategory, notes?: string) => invoke<ReferenceImage>("import_reference_image", { worktreeId, sourcePath, category, notes }),
  importReferenceBytes: (worktreeId: string, fileName: string, bytes: number[], category: ReferenceCategory, notes?: string) => invoke<ReferenceImage>("import_reference_bytes", { worktreeId, fileName, bytes, category, notes }),
  updateReferenceImage: (id: string, name: string, category: ReferenceCategory, notes?: string) => invoke<ReferenceImage>("update_reference_image", { id, name, category, notes }),
  deleteReferenceImage: (id: string) => invoke<void>("delete_reference_image", { id }),
  setConversationReference: (conversationId: string, referenceId: string, active: boolean, strength?: number) => invoke<void>("set_conversation_reference", { conversationId, referenceId, active, strength }),
  listConversationReferenceIds: (conversationId: string) => invoke<string[]>("list_conversation_reference_ids", { conversationId }),
  listAnimations: (workspaceId: string, worktreeId?: string) => invoke<Animation[]>("list_animations", { workspaceId, worktreeId: worktreeId ?? null }),
  saveAnimation: (input: AnimationInput) => invoke<Animation>("save_animation", { input }),
  deleteAnimation: (id: string) => invoke<void>("delete_animation", { id }),
  exportAnimation: (id: string, destination?: string) => invoke<ExportResult>("export_animation", { id, destination }),
  listJobs: (projectId: string, worktreeId?: string) => invoke<BackgroundJob[]>("list_jobs", { projectId, worktreeId: worktreeId ?? null }),
  cancelJob: (id: string) => invoke<BackgroundJob>("cancel_job", { id }),
  listSpriteSheets: (projectId: string, worktreeId?: string) => invoke<SpriteSheet[]>("list_sprite_sheets", { projectId, worktreeId: worktreeId ?? null }),
  queueSpriteSheet: (input: SpriteSheetInput) => invoke<BackgroundJob>("queue_sprite_sheet", { input }),
  deleteSpriteSheet: (id: string) => invoke<void>("delete_sprite_sheet", { id }),
  listVfxEffects: (projectId: string, worktreeId?: string) => invoke<VfxEffect[]>("list_vfx_effects", { projectId, worktreeId: worktreeId ?? null }),
  queueProceduralVfx: (input: ProceduralVfxInput) => invoke<BackgroundJob>("queue_procedural_vfx", { input }),
  getQualityReport: (animationId: string) => invoke<QualityReport | null>("get_quality_report", { animationId }),
  queueQualityAnalysis: (animationId: string) => invoke<BackgroundJob>("queue_quality_analysis", { animationId }),
  acknowledgeQualityCheck: (checkId: string, ignored = false) => invoke<void>("acknowledge_quality_check", { checkId, ignored }),
  optimizeAnimationFrames: (animationId: string, maxChanges = 3) => invoke<FrameOptimizationResult>("optimize_animation_frames", { input: { animationId, maxChanges } }),
  repairAnimationAlignment: (animationId: string) => invoke<Animation>("repair_animation_alignment", { animationId }),
  listRigs: (workspaceId: string, worktreeId?: string) => invoke<Rig[]>("list_rigs", { workspaceId, worktreeId: worktreeId ?? null }),
  saveRig: (input: RigInput) => invoke<Rig>("save_rig", { input }),
  deleteRig: (id: string) => invoke<void>("delete_rig", { id }),
  validateRigSpec: (input: RigInput) => invoke<string[]>("validate_rig_spec", { input }),
  suggestRigPoints: (assetId: string, morphology?: string) => invoke<RigSuggestion>("suggest_rig_points", { assetId, morphology: morphology ?? null }),
  analyzeRigFit: (assetId: string) => invoke<RigFitReport>("analyze_rig_fit", { assetId }),
  aiSuggestRigPoints: (input: { assetId: string; morphology?: string; motion?: string; providerId?: string; model?: string; reasoningEffort?: string }) => invoke<RigSuggestion>("ai_suggest_rig_points", { input }),
  renderRigPreview: (input: RigInput) => invoke<string[]>("render_rig_preview", { input }),
  renderRigAnimation: (input: RigInput) => invoke<RigRenderResult>("render_rig_animation", { input }),
  listAnimationTemplates: (projectId: string) => invoke<AnimationTemplate[]>("list_animation_templates", { projectId }),
  createAnimationTemplate: (animationId: string, name: string, intent: string, motionDescription: string, frameMode: "fixed" | "auto", minFrames: number, maxFrames: number, generationPrompt = "", negativePrompt = "") => invoke<AnimationTemplate>("create_animation_template", { animationId, name, intent, motionDescription, frameMode, minFrames, maxFrames, generationPrompt, negativePrompt }),
  applyAnimationTemplate: (templateId: string, targetAssetId: string) => invoke<TemplateApplication>("apply_animation_template", { templateId, targetAssetId }),
  deleteAnimationTemplate: (id: string) => invoke<void>("delete_animation_template", { id }),
  getSetting: (key: string) => invoke<unknown>("get_setting", { key }),
  setSetting: (key: string, value: unknown) => invoke<void>("set_setting", { key, value }),
};

export const assetUrl = (path: string) => convertFileSrc(path);
