<script lang="ts">
  import { BookImage, Bone, Boxes, Clapperboard, Gamepad2, Grid3X3, Images, Map, Sparkles } from "lucide-svelte";
  let { active, counts, onSelect }:{active:string;counts:{sprites:number;references:number;animate:number;rigs:number;packs:number};onSelect:(id:string)=>void}=$props();
  const items=$derived([{id:"sprites",label:"Sprites",icon:Images,count:counts.sprites},{id:"references",label:"References",icon:BookImage,count:counts.references},{id:"animate",label:"Animations",icon:Clapperboard,count:counts.animate},{id:"rig",label:"Rig",icon:Bone,count:counts.rigs},{id:"terrain",label:"Terrain",icon:Map,count:0},{id:"vfx",label:"VFX",icon:Sparkles,count:0},{id:"sheets",label:"Sheets",icon:Grid3X3,count:0},{id:"packs",label:"Packs",icon:Boxes,count:counts.packs},{id:"play",label:"Playground",icon:Gamepad2,count:0}]);
</script>
<header><div><span>MEDIA GALLERY</span><strong>Project assets</strong></div><nav>{#each items as item}{@const Icon=item.icon}<button class:active={active===item.id} onclick={()=>onSelect(item.id)}><Icon size={13}/>{item.label}{#if item.count}<small>{item.count}</small>{/if}</button>{/each}</nav></header>
<style>
  header{height:58px;min-height:58px;border-bottom:1px solid var(--border);background:var(--sidebar);display:flex;align-items:center;justify-content:space-between;padding:0 16px 0 20px;gap:20px}header>div span,header>div strong{display:block}header>div span{font-size:8px;letter-spacing:.15em;color:var(--accent);font-weight:700}header>div strong{font-size:12px;margin-top:4px}nav{height:100%;display:flex;align-items:center;gap:2px;overflow:auto}nav button{height:34px;border:0;border-radius:6px;background:transparent;color:var(--faint);display:flex;align-items:center;gap:6px;padding:0 9px;font:inherit;font-size:11px;white-space:nowrap;cursor:pointer}nav button:hover,nav button.active{background:var(--surface-hover);color:var(--text)}nav small{min-width:17px;height:17px;padding:0 4px;border-radius:9px;background:var(--surface);display:grid;place-items:center;font-size:9px}@media(max-width:930px){header>div{display:none}header{padding-left:10px}}
</style>
