<script lang="ts">
  import { untrack } from "svelte";
  import { X } from "lucide-svelte";
  import type { FrameMode } from "$lib/types";
  let { animationName, frameCount, busy=false, onCreate, onClose }: {animationName:string;frameCount:number;busy?:boolean;onCreate:(value:{name:string;intent:string;motionDescription:string;frameMode:FrameMode;minFrames:number;maxFrames:number;generationPrompt:string;negativePrompt:string})=>void|Promise<void>;onClose:()=>void}=$props();
  let name=$state(untrack(()=>animationName.replace(/[_-]+/g," ").replace(/\b\w/g,value=>value.toUpperCase())));
  let intent=$state(untrack(()=>animationName.replace(/[_-]+/g," ")));
  let motionDescription=$state(untrack(()=>`Reproduce the complete ${animationName.replace(/[_-]+/g," ")} motion with coherent anticipation, action, follow-through, and recovery.`));
  let frameMode=$state<FrameMode>("auto");
  let minFrames=$state(untrack(()=>Math.max(2,frameCount-2)));
  let maxFrames=$state(untrack(()=>Math.min(64,frameCount+6)));
  let generationPrompt=$state("");
  let negativePrompt=$state("identity drift, palette drift, camera change, disconnected limbs, duplicate poses");
  const submit=()=>onCreate({name,intent,motionDescription,frameMode,minFrames,maxFrames,generationPrompt,negativePrompt});
</script>
<div class="backdrop" role="presentation" onclick={(event)=>event.target===event.currentTarget&&onClose()}><section class="dialog"><header><div><p>MOTION TEMPLATE</p><h2>Reuse this animation on other assets</h2></div><button onclick={onClose}><X size={15}/></button></header><div class="form"><label>Name<input bind:value={name}/></label><label>Intent<input bind:value={intent}/></label><label>Motion description<textarea bind:value={motionDescription} rows="3"></textarea></label><div class="row"><label>Frame policy<select bind:value={frameMode}><option value="auto">Auto</option><option value="fixed">Fixed</option></select></label><label>Minimum<input type="number" min="1" max="64" bind:value={minFrames}/></label><label>Maximum<input type="number" min="1" max="64" bind:value={maxFrames}/></label></div><label>Generation guidance<textarea bind:value={generationPrompt} rows="2" placeholder="Optional extra instructions"></textarea></label><label>Negative constraints<textarea bind:value={negativePrompt} rows="2"></textarea></label></div><footer><button onclick={onClose}>Cancel</button><button class="primary" disabled={busy||!name.trim()||!intent.trim()||!motionDescription.trim()} onclick={submit}>{busy?"Saving…":"Save template"}</button></footer></section></div>
<style>.backdrop{position:fixed;inset:0;z-index:70;background:#000a;display:grid;place-items:center}.dialog{width:min(560px,calc(100vw - 30px));max-height:calc(100vh - 30px);overflow:auto;background:var(--surface);border:1px solid var(--border-strong);border-radius:10px;box-shadow:0 28px 90px #000b;padding:20px}header{display:flex;align-items:flex-start;justify-content:space-between}header p{font-size:9px;letter-spacing:.15em;font-weight:700;color:var(--accent);margin:0 0 7px}h2{font-size:17px;margin:0}header button{border:0;background:transparent;color:var(--faint);cursor:pointer}.form{display:grid;gap:12px;margin-top:20px}.form label{font-size:10px;color:var(--muted)}input,textarea,select{width:100%;margin-top:5px;background:var(--bg);border:1px solid var(--border);border-radius:5px;color:var(--text);font:inherit;font-size:11px;padding:8px;outline:0}input,select{height:32px;padding:0 8px}textarea{resize:vertical;line-height:1.45}.row{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:8px}footer{display:flex;justify-content:flex-end;gap:7px;border-top:1px solid var(--border);padding-top:15px;margin-top:18px}footer button{height:31px;border:1px solid var(--border);border-radius:5px;background:var(--bg);color:var(--muted);font:inherit;font-size:11px;padding:0 11px;cursor:pointer}footer button.primary{background:var(--text);color:var(--bg);border-color:var(--text)}button:disabled{opacity:.45}</style>
